Reading/Reading/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^tmt/',include('tmt.urls',namespace='tmt')),
]

Reading/tmt/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
url(r'^$',views.index,name='index'),
url(r'^testing/$',views.deal,name='testing'),
url(r'^submit/$',views.calculate,name='submit'),
url(r'^(?P<question_id>[0-9]+)/$',views.deal,name='deal'),
]

Reading/tmt/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

class Question(models.Model):
	question_text = models.CharField(max_length=200)
	attribute = models.CharField(max_length=12)	
	project = models.CharField(max_length=32,default ="")
	project_id = models.CharField(max_length=12,default="")
	def __unicode__(self):
		return self.question_text
# Create your models here.

Reading/Reading/views.py
#-*-coding:utf-8-*-
from django.http import HttpResponse
from django.shortcuts import render,get_object_or_404

def index(request):
	response_content = '''<p>hello world! this is the Django web service connectted with Apache.</p>
<h1>气质测试临时站点</h1>
<code>author: SnowmanZhang</code>
<h4>点击下方链接进入测试页面</h4>
<a href="./tmt/">进入</a>
'''
	
	return render(request,"index.html")

Reading/tmt/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render,get_object_or_404
from django.template import RequestContext,loader
from .models import Question
from django.http import HttpResponse

def deal(request):
	question_id = request.session['pagenumber']
	p = get_object_or_404(Question,project_id=question_id)
	request.session['pagenumber'] = request.session['pagenumber'] + 1
	if request.POST and request.POST.has_key('choice'):
		if request.POST['choice'] == "":
			pass
		else:
			request.session['dict_choice'][question_id] = request.POST['choice']
	else:
		request.session['pagenumber'] = request.session['pagenumber'] - 1 
		return render(request,'tmt/ss_input.html',{'s_question':p,'pagenumber':request.session['pagenumber'],})
	if question_id < 60:
		pnext = get_object_or_404(Question,project_id=str(int(question_id)+1))
	else:
		pnext = p
	return render(request,'tmt/ss_input.html',{'s_question':pnext,'pagenumber':request.session['pagenumber'],})


def calculate(request):
	dict_choice = request.session['dict_choice']
	score_tree = {'1':0,'2':0,'3':0,'4':0}
	for unit in dict_choice:
		attr = get_object_or_404(Question,project_id = unit).attribute
		score_tree[attr] = score_tree[attr] - int(dict_choice[unit]) + 3
	scorelist = [score_tree['1'],score_tree['2'],score_tree['3'],score_tree['4']]
	temp = scorelist[:]
	temp.sort()
	enddict = {'胆汁质':score_tree['1'],'多血质':score_tree['2'],'黏液质':score_tree['3'],'抑郁质':score_tree['4'],}
	res_dict = ['胆汁质','多血质','黏液质','抑郁质']
	if temp[-1] - temp[-2] > 4:
		result = res_dict[scorelist.index(temp[-1])]
	elif temp[-2] - temp[-3] > 4:
		result = res_dict[scorelist.index(temp[-1])]
		scorelist[scorelist.index(temp[-1])] = -50
		result = result + '+' + res_dict[scorelist.index(temp[-2])] 
	elif temp[-3] - temp[-4] > 4:
		result = res_dict[scorelist.index(temp[-1])]
		scorelist[scorelist.index(temp[-1])] = -50
		result = result + '+' + res_dict[scorelist.index(temp[-2])] 
		scorelist[scorelist.index(temp[-2])]
		result = result + '+' + res_dict[scorelist.index(temp[-3])]
	else:
		result = "混合气质"
	if len(dict_choice) > 10:
		with open("/home/tmtlog.txt",'a') as f:
			for key,value in dict_choice.items():
				f.write(key+','+value+'\t')
			f.write('\n')
	return render(request,'tmt/result.html',{'score_tree':enddict,'result':result,})

def index(request):
	request.session['dict_choice'] = {}
	request.session['pagenumber'] = 1
	return render(request,'tmt/tmtindex.html')


# Create your views here.

Reading/templates/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
	{% load static %}
    <link rel="icon" href="{% static 'dist/image/icon_snowman.ico' %}">

    <title>冬雪又一年|Time after time</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'dist/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{% static 'dist/css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{% static 'dist/js/ie-emulation-modes-warning.js' %}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Custom styles for this template -->
    <link href="{% static 'dist/css/carousel.css' %}" rel="stylesheet">
  </head>
<!-- NAVBAR
================================================== -->
  <body>
    <div class="navbar-wrapper">
      <div class="container">

        <nav class="navbar navbar-inverse navbar-static-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#">Snowman</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li class="active"><a href="#">Home</a></li>
                <li><a href="#about">About</a></li>
                <li><a href="#contact">Contact</a></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Project<span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="#">气质类型测试</a></li>
                  </ul>
                </li>
              </ul>
            </div>
          </div>
        </nav>

      </div>
    </div>


    <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img class="first-slide" src="{% static 'dist/image/1.png' %}" alt="First slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Thanks for browsing!</h1>
              <p>This site is my Django practice project, it has some interesting small projects, please click the button below for details.:)</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="second-slide" src="{% static 'dist/image/2.jpg' %}" alt="Second slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Thanks for browsing!</h1>
              <p>This site is my Django practice project, it has some interesting small projects, please click the button below for details.:)</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="third-slide" src="{% static 'dist/image/3.jpg' %}" alt="Third slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Thanks for browsing!</h1>
              <p>This site is my Django practice project, it has some interesting small projects, please click the button below for details.:)</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div><!-- /.carousel -->


    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <div class="container marketing">

      <!-- Three columns of text below the carousel -->
      <div class="row">
        <div class="col-lg-4">
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="img-circle" src="{% static 'dist/image/head1.jpg' %}" alt="Generic placeholder image" width="140" height="140">
          <h2>气质类型测试</h2>
          <p>根据希波克拉底的四液说，人的气质类型分为：多血质、粘液质、抑郁质和胆汁质。分别对应着人们气质行为的四种类别，随着生活变化，人的气质类型也会发生变化，你是哪一种气质呢？使用官方标准测试来看一看吧！</p>
          <p><a class="btn btn-default" href="/tmt/" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
        </div><!-- /.col-lg-4 -->
      </div><!-- /.row -->

      <!-- FOOTER -->
      <footer>
        <p class="pull-right"><a href="#">Back to top</a></p>
        <p>&copy; 2017 SnowmanZhang &middot;</p>
      </footer>

    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'dist/js/jquery.min.js' %}"></script>
    <script src="{% static 'dist/js/bootstrap.min.js' %}"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="{% static 'dist/js/holder.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'dist/js/ie10-viewport-bug-workaround.js' %}"></script>
  </body>
</html>

Reading/tmt/templates/tmt/response.html
<h3>the question is {{ s_question.question_text }}</h3>
<h4>your choice is {{ has_choice }}</h4>

Reading/tmt/templates/tmt/result.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
{% load static %}
    <link rel="icon" href="{% static 'dist/image/icon_snowman.ico' %}">

    <title>气质测试|首页</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'dist/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{% static 'dist/css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'dist/css/navbar-static-top.css' %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{% static 'dist/js/ie-emulation-modes-warning.js' %}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container">

      <!-- Main component for a primary marketing message or call to action -->
      <div class="jumbotron">
        <h3>您的气质类型是 {{ result }}</h3>
	{% for key,value in score_tree.items %}
		<p>您的 {{ key }} 得分为 {{ value }}</p>
	{% endfor %}
        <p>胆汁质：直率、热情、具有快速的反应力，行动敏捷，情绪冲动，具有克服困难、坚忍不拔的意志，但不考虑是否成功，易爆发、狂热，不可抑制，具有外倾性，但若精力耗尽便会失去信心。
矫正：着重发扬开朗、豪放、进取的特点。注意控制感情，培养耐心，自控能力，要谦虚，多听他人意见，沉着冷静，防止产生任性、粗暴、高傲的不良品质。</p>
	<p>多血质：敏捷好动、善于交际、反应灵敏，在新环境里不拘束，在工作学习上精力充沛，且效率高，表现出机敏的工作能力，善于适应变化的新环境，在集体中心神愉快，朝气蓬勃，具有外倾性，使人对什么都感兴趣。但情感易变，缺乏持久力，这类人可以成为有效的活动家，领导家。
矫正：发扬热情、活泼、机敏、灵活的品质，加强恒心的培养，行动不易轻率，三思而后行，防止产生自由散漫、见异思迁的感情。</p>
	<p>黏液质：安静、稳重、沉着、沉默寡言、三思而行，生活中是坚持而稳重的工作者，严于遵守既定的生活秩序，工作制度，不为外因而分心，态度上持重，不易激动或转移注意力。
矫正：着重发扬坚定、踏实、诚恳的优良品质，多参加运动，培养主动性，防止产生慎小偏微、因循守旧的品行。</p>
	<p>抑郁质：情趣体验深刻，行动迟缓，往往为微不足道的事情动感情，具有高度的情趣，敏感性，对外部环境敏感，易产生幻想、胆小、孤僻、恐惧。
矫正：着重发扬心细、机警、稳重的品质，加强主动性、积极性的培养，勇于面对挫折，提高自己的胆量，多参加活动，培养自信心，防止产生孤僻自卑的不良品行。</p>

      </div>

    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'dist/js/jquery.min.js' %}"></script>
    <script src="{% static 'dist/js/bootstrap.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'dist/js/ie10-viewport-bug-workaround.js' %}"></script>
  </body>
</html>

Reading/tmt/templates/tmt/s_input.html
<html>
<head>
<title>{{ s_question }}</title>
</head>
<body>
{% if s_question %}
<form action="{% url 'tmt:deal' s_question.id %}" method="post">	
<strong>{{ s_question.question_text }}</strong><br />
{% csrf_token %}
<input type="radio" name="choice" id="choice1" value="1"/><label for="choice1">非常符合</label><br />
<input type="radio" name="choice" id="choice2" value="2"/><label for="choice2">比较符合</label><br />
<input type="radio" name="choice" id="choice3" value="3"/><label for="choice3">不确定</label><br />
<input type="radio" name="choice" id="choice4" value="4"/><label for="choice4">比较不符合</label><br />
<input type="radio" name="choice" id="choice5" value="5"/><label for="choice5">完全不符合</label><br />
<input type="submit" value="Vote" />
	 

</form>
{% endif %}

</body>
</html>

Reading/tmt/templates/tmt/ss_input.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
{% load static %}

    <link rel="icon" href="{% static 'dist/image/icon_snowman.ico' %}">
    <title>第 {{ pagenumber }} 题</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'dist/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{% static 'dist/css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'dist/css/jumbotron-narrow.css' %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{% static 'dist/js/ie-emulation-modes-warning.js' %}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
{% if s_question %}
<form action="{% url 'tmt:testing' %}" method="post">	
{% csrf_token %}
    <div class="container">
      <div class="header clearfix">
        <nav>
          <ul class="nav nav-pills pull-right">
            <li role="presentation" class="active"><a href="{% url 'tmt:submit' %}" class="btn btn-lg btn-success" >提前提交</a></li>
            <li role="presentation" class="active"><button type="submit"  name="choice" id="choice0" class="btn btn-lg"  value="">跳过此题</button></li>
          </ul>
        </nav>
        <h3 class="text-muted">性格测试</h3>
      </div>


{% ifnotequal pagenumber 61 %}
      <div class="jumbotron">
        <h3>{{ s_question.question_text }}</h3>
      </div>


      <div class="row">
        <div class="col-lg-8">
        	<p><button type="submit" name="choice" class="btn btn-lg btn-success"  id="choice1" value="1"/>非常符合</button></p>
        </div><!-- /.col-lg-6 -->
        <div class="col-lg-8">
          	<p><button type="submit" name="choice" class="btn btn-lg btn-success"  id="choice2" value="2"/>比较符合</button></p>
        </div><!-- /.col-lg-6 -->
        <div class="col-lg-8">
        	<p><button type="submit" name="choice" class="btn btn-lg btn-success"  id="choice3" value="3"/>不能确定</button></p>
        </div><!-- /.col-lg-6 -->
        <div class="col-lg-8">
          	<p><button type="submit" name="choice" class="btn btn-lg btn-success"  id="choice4" value="4"/>较不符合</button></p>
        </div><!-- /.col-lg-6 -->
        <div class="col-lg-8">
        	<p><button type="submit" name="choice" class="btn btn-lg btn-success"  id="choice5" value="5"/>完全不符</button></p>
        </div><!-- /.col-lg-6 -->
      </div><!-- /.row -->
{% else %}
	<div class="row">
		<div class="col-lg-3">
			<p><a name="choice" class="btn btn-lg btn-success" href="{% url 'tmt:submit' %}">提交</a></p>
		</div>
	</div>
{% endifnotequal %}


</form>
{% endif %}

      <footer class="footer">
        <p>&copy; 2017 SnowmanZhang</p>
      </footer>

    </div> <!-- /container -->


    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'dist/js/ie10-viewport-bug-workaround.js' %}"></script>
  </body>
</html>

Reading/tmt/templates/tmt/tmtindex.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
{% load static %}
    <link rel="icon" href="{% static 'dist/image/icon_snowman.ico' %}">

    <title>气质测试|首页</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'dist/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{% static 'dist/css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'dist/css/navbar-static-top.css' %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{% static 'dist/js/ie-emulation-modes-warning.js' %}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container">

      <!-- Main component for a primary marketing message or call to action -->
      <div class="jumbotron">
        <h1>气质测试简介</h1>
        <p>根据希波克拉底的四液说，人的气质类型分为：多血质、粘液质、抑郁质和胆汁质。分别对应着人们气质行为的四种类别，随着生活变化，人的气质类型也会发生变化。测试题共60题整，本站经过前期数据优化，可以以尽可能少的题目数量得知您的气质类型，但我们更加推荐您做完这60道题获得最准确的判断。</p>
        <p>
          <a class="btn btn-lg btn-primary" href="./testing/" role="button">开始答题</a>
        </p>
      </div>

    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'dist/js/jquery.min.js' %}"></script>
    <script src="{% static 'dist/js/bootstrap.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'dist/js/ie10-viewport-bug-workaround.js' %}"></script>
  </body>
</html>